name: CI Pipeline

on:
  push:
    branches: [main, ci-setup]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Download Codacy CLI
        run: |
          curl -Ls https://github.com/codacy/codacy-analysis-cli/releases/latest/download/codacy-analysis-cli-linux -o codacy-analysis-cli
          chmod +x codacy-analysis-cli

      - name: Run Codacy static analysis
        run: ./codacy-analysis-cli analyze -t ${{ secrets.CODACY_PROJECT_TOKEN }}

